# Generated by Django 3.2.7 on 2021-09-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_config", "0004_blogdata_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogdata",
            name="logo",
            field=models.ImageField(
                blank=True,
                default="images/logo/default.png",
                help_text="Upload a product image",
                null=True,
                upload_to="images/logo",
                verbose_name="image",
            ),
        ),
    ]
