# Generated by Django 3.2.7 on 2021-09-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_config', '0005_alter_blogdata_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('facebook_url', models.CharField(max_length=255)),
                ('twitter_url', models.CharField(max_length=255)),
                ('instagram_url', models.CharField(max_length=255)),
                ('youtube_url', models.CharField(max_length=255)),
                ('github_url', models.CharField(max_length=255)),
                ('linkedin_url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'AboutMe',
            },
        ),
    ]
