# Generated by Django 3.2.7 on 2021-09-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_config', '0007_auto_20210909_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='brief',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
