# Generated by Django 3.2.7 on 2021-09-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_config', '0008_aboutme_brief'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='brief',
        ),
    ]
