# Generated by Django 3.2.7 on 2021-09-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_config', '0005_alter_blogdata_logo'),
        ('posts', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='blog_config.Category'),
        ),
    ]
